name = "billing-engine"
main = "src/index.ts"
account_id = "c5b2c37002a5f34a63f7d8c10acffff7"
workers_dev = true
compatibility_date = "2024-10-05"

[observability]
enabled = true

[[kv_namespaces]]
binding = "INVOICE_KV"
id = "0ece6534e7e641a297ef145fff3c3fd9"

[env.dev]
workers_dev = true
compatibility_date = "2024-10-06"
vars.SUBSCRIPTION_WORKER_URL = "http://localhost:8787/api/v0.1"
vars.PAYMENT_WORKER_URL = "http://localhost:37069/api/v0.1"
vars.NOTIFICATION_WORKER_URL = "http://localhost:33523/api/v0.1"
kv_namespaces = [
    { binding = "INVOICE_KV", id = "0ece6534e7e641a297ef145fff3c3fd9" },
]

[env.production]
vars.SUBSCRIPTION_WORKER_URL = "http://subscription.azam-arid1144.workers.dev/api/v0.1"
vars.PAYMENT_WORKER_URL = "http://payment-processing.azam-arid1144.workers.dev//api/v0.1"
vars.NOTIFICATION_WORKER_URL = "http://notification.azam-arid1144.workers.dev/api/v0.1"
kv_namespaces = [
    { binding = "INVOICE_KV", id = "0ece6534e7e641a297ef145fff3c3fd9" },
]